# -*- mode: ruby -*-
# vi: set ft=ruby :
#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
# Require YAML module
require 'yaml'

config = YAML.load_file(File.join(File.dirname(__FILE__), 'config.yml'))

base_flavour=config['environment']['base_flavour']

base_box=config['environment']['base_box']

base_box_version=config['environment']['base_box_version']

domain=config['environment']['domain']

boxes = config['boxes']

boxes_hostsfile_entries=""

boxes_hosts=""

 boxes.each do |box|
   boxes_hostsfile_entries=boxes_hostsfile_entries+box['mgmt_ip'] + ' ' +  box['name'] + ' ' + box['name']+'.'+domain+'\n'
   boxes_hosts=boxes_hosts+box['mgmt_ip'] + ' '
  end

docker_engine_version=config['environment']['docker_engine_version']
kubernetes_version=config['environment']['kubernetes_version']
kubernetes_token=config['environment']['kubernetes_token']


update_hosts = <<SCRIPT
    echo "127.0.0.1 localhost" >/etc/hosts
    echo -e "#{boxes_hostsfile_entries}" |tee -a /etc/hosts
SCRIPT


####### REDHAT-like

rhn_disable_autoupdates = <<SCRIPT
  systemctl stop packagekit
  systemctl mask packagekit
SCRIPT

rh_install_common_software  = <<SCRIPT
  systemctl stop packagekit
  systemctl mask packagekit
  yum install -y -q -e 0 \
  ntpdate \
  ntp \
  python \
  git \
  && timedatectl set-timezone Europe/Madrid
SCRIPT

Vagrant.configure(2) do |config|
  VAGRANT_COMMAND = ARGV[0]
  config.vm.box = base_box
  config.vm.box_version = base_box_version
  config.vm.synced_folder "../keys/", "/keys",create:true

  boxes.each do |node|
    config.vm.define node['name'] do |config|
      config.vm.hostname = node['name']
      config.vm.provider "virtualbox" do |v|
	      v.linked_clone = true
        config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
	      v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
        v.name = node['name']
        v.customize ["modifyvm", :id, "--memory", node['mem']]
        v.customize ["modifyvm", :id, "--cpus", node['cpu']]

        v.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
        v.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
        v.customize ["modifyvm", :id, "--nictype3", "Am79C973"]
        v.customize ["modifyvm", :id, "--nictype4", "Am79C973"]
        v.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        v.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      config.vm.network "private_network",
      ip: node['mgmt_ip'],:netmask => "255.255.255.0",
      virtualbox__intnet: false,
      hostonlyadapter: ["vboxnet1"]

      config.vm.network "private_network",
        ip: node['hostonly_ip']

       config.vm.provision :shell, :inline => update_hosts

      config.vm.provision :shell, :inline => rhn_disable_autoupdates

      config.vm.provision :shell, :inline => rh_install_common_software

    end

  end


end
